### ISSUE TITLE
passive-dns Not Found

### ISSUE THREAD

**Issue by emhohensee** [JustinAzoff/bro-pdns#4]
In the go-rewrite branch  the __load__.bro file contains a reference to a .bro file called passive-dns that doesn't exist. I checked the master branch and it exists there. Is the go-rewrite branch workable yet?

**Comment by JustinAzoff** [comment]
Oh, yes!  I should remove those files.  I designed the go version to not require any bro integration... having it integrated in bro turned out to be too fragile.

The new version is designed so that you can just run bro-pdns index against the existing dns archived log files as they are created.

You just need to stick something like this in cron:

    find /bro/log/archive/directory/ -mtime -2 -name 'dns*.gz'  | xargs -n 30 bro-pdns index 2>&1

**Comment by emhohensee** [comment]
So, if I'm understanding correctly, I still need bro installed and sniffing for DNS traffic but bro-pdns is no longer a bro module. It just reads the dns.log files that bro spits out?

**Comment by JustinAzoff** [comment]
Sounds good.  Let me know if you run into any issues.  I know I have an open issue to add support for json logs, but as long as you're using the default ascii logs it should just work.
